const eventProcessNodes=['识别报告','任务分派','事实评估','方案执行','复核验证','办结归档'];
const eventTableColumns=['机构','风险类型','事件名称','发生日期','上报日期','关注等级','当前流程环节','处置状态','操作'];
// Report narratives and materials are fictional, keyed to the existing event fixtures.
const eventScenarios={
 'E-001':{cause:'客户融资续接和资产回款期限存在错配，需逐笔核实展期范围、到期安排及现金流缺口。',root:'跨机构债权与债券投资的信息更新不同步，需统一主体标识并核对回款来源，不能仅凭融资展期信息认定违约。',impact:'可能影响相关债权和债券投资的回款时点，并通过共同客户敞口向多家持有机构传导。重点关注可用现金、担保有效性及资金可转移性。',objective:'查清共同客户回款及融资安排，落实分机构缓释措施，持续跟踪流动性和资产质量变化。',measures:[['核对存续资产与回款安排','逐笔核对债权、债券、到期日和抵质押物，确认统一客户ID与持有机构。','资产核对清单'],['落实回款与缓释措施','跟踪回款计划、担保追索和展期条件；需要调整敞口的，按授权落实具体安排。','回款安排及缓释措施台账'],['续报现金流与剩余风险','持续报告实际回款、计划偏差和剩余敞口；出现重大变化时及时补报。','执行进展及资金核验记录']],update:'已完成共同客户和相关资产清单核对，正在落实分机构回款及缓释安排。回款结果仍待后续验证。'},
 'E-002':{cause:'市场波动和组合敏感度变化导致市场风险限额使用率触发内部红灯，需核对持仓、计量参数及限额版本。',root:'需区分真实敞口上升、计量参数变化与数据口径偏差，评估存量组合调整及限额前置控制是否充分。',impact:'可能增加组合估值波动和市场风险敞口；内部限额超限不直接等同于发生损失或违反监管规定。',objective:'核实超限原因和计量结果，在经确认的交易及限额约束下调整敞口，并验证调整效果。',measures:[['复核持仓与超限计算','核对风险因子、交易头寸、计量参数和有效限额版本。','超限复算核对表'],['实施敞口压降','按确认方案调整组合和对冲安排，避免因集中处置引入额外流动性风险。','组合调整与交易执行记录'],['复测限额与监测效果','按调整后的持仓持续复算，核验当前占用及剩余风险。','限额复测与执行报告']],update:'已完成持仓和限额口径核对，当前正执行组合调整；内部限额占用仍需持续监测，尚不具备办结条件。'},
 'E-003':{cause:'存量项目约定回款与实际到账出现偏差，机构正在补充合同约定、催收记录及资产处置材料。',root:'需核实项目现金流变化、处置进度和回款凭证完整性，区分回款延期、登记差错与实质偿付风险。',impact:'可能影响项目回收周期、减值判断和资金安排；是否形成实际损失需根据合同及可回收金额另行认定。',objective:'查清回款偏差原因，完善追偿和处置安排，形成可核验的责任清单与后续回款节点。',measures:[['补齐回款与担保材料','提交合同、到期安排、到账凭证及担保现状，完成事实核查。','项目回款核查材料'],['完善追偿与处置方案','结合核查结果确定催收、担保追索和资产处置安排，履行内部审议。','项目处置方案'],['跟踪执行与回收情况','记录实际回款、处置进度和计划偏差，补充减值判断依据。','回款及处置进度表']],update:'已报送初步回款偏差情况，合同条款及担保材料仍在补充；处置方案为草案，尚未进入执行。'},
 'E-004':{cause:'客户经营承压线索触发授信与投资资产质量专项核查，需验证经营资料与实际偿付情况。',root:'需核对最新财务信息、债务到期结构和担保有效性，排查外部信息与内部客户档案是否一致。',impact:'重点评估授信回收、债券投资和担保风险；投资账面余额不替代全部授信风险暴露，尚未认定损失。',objective:'核实资产质量变化和潜在影响范围，明确客户跟踪、风险缓释及后续报告安排。',measures:[['完成客户事实核验','核对经营数据、授信余额、投资资产及到期情况。','客户资产质量核验底稿'],['提出分类应对措施','区分授信和投资业务，制定监测、担保核验和敞口管理措施。','分类应对方案'],['跟踪偿付与质量变化','按确认频率更新回款、评级和资产质量变化，必要时提请进一步处置。','资产质量跟踪报告']],update:'专项核查已启动，正在核对经营资料与内部资产记录；需完成事实评估后再确认最终处置方案。'},
 'E-005':{cause:'内部市场风险限额占用触发红灯，需结合市场波动、持仓集中度和计量口径确认原因。',root:'需进一步校核头寸调整与限额监测的衔接，确认风险因子变动是否及时反映到日常管理中。',impact:'重点关注市场敞口、估值波动和交易调整对流动性的联动影响；不以敞口规模直接推算实际损失。',objective:'落实市场风险敞口调整，确保执行过程可追溯，并持续核验限额占用和剩余风险。',measures:[['核对风险敞口与限额','对账交易头寸、计量结果和限额生效版本。','风险敞口核对表'],['分步调整组合敞口','按确认方案落实交易调整和必要的风险缓释，记录执行依据。','敞口调整执行台账'],['验证调整结果','复算调整后的指标，跟踪风险因子变化与方案效果。','调整效果复核记录']],update:'敞口核对已完成，组合调整正在执行；当前指标仍为红灯，需持续跟踪调整效果。'},
 'E-006':{cause:'共同客户跨机构持有记录存在主体匹配和资产范围核对需求，需排除口径不一致对集中度判断的影响。',root:'统一主体ID、业务资产标识与计量范围之间的映射需要复核，不同机构持有的独立债权不能作为重复记录扣除。',impact:'可能影响共同客户集中度展示和集团敞口判断。已进入复核环节不代表各机构单体集中度均已恢复正常。',objective:'核实共同客户身份、持有资产和计量结果，完成数据及口径复核，明确残余风险跟踪要求。',measures:[['核对共同客户映射','核对统一客户ID、别名和相关持有机构，确认客户归并关系。','统一客户映射核验表'],['复核持有资产与计量','按底层资产逐项核对余额和去重依据，保留各机构独立债权。','跨机构资产核对及复算底稿'],['核验结论与持续监测','确认差异解释及整改证据，并对仍触发预警的单体指标继续跟踪。','集中度复核意见']],update:'客户映射及持有资产核对已完成，当前处于复核验证；仍需确认差异处理及后续监测安排，尚未办结。'}
};
function eventRiskLabel(cat){return warningIndicatorTypes.find(([id])=>id===cat)?.[1]||'其他风险'}
function eventDay(e,offset=0,time='10:30'){return e.period+'-'+String(Math.min(e.day+offset,Number(monthEnd(e.period).slice(-2)))).padStart(2,'0')+' '+time}
function eventListItems(args={}){
 const query=(args.query||'').trim().toLowerCase();
 return eventsData().filter(e=>(!args.org||args.org==='all'||e.orgs.includes(args.org))&&(!args.category||args.category==='all'||(warningIndicatorTypes.some(([id])=>id===e.cat)?e.cat:'other')===args.category)&&(!args.level||args.level==='all'||e.level===args.level)&&(!args.status||args.status==='all'||e.status===args.status)&&(e.title+e.id+e.orgs.map(o=>ORGS[o].name).join('')).toLowerCase().includes(query))
  .sort((a,b)=>orgOrder.indexOf(a.orgs[0])-orgOrder.indexOf(b.orgs[0])||warningIndicatorTypes.findIndex(c=>c[0]===a.cat)-warningIndicatorTypes.findIndex(c=>c[0]===b.cat)||b.reportTime.localeCompare(a.reportTime));
}
function eventListResults(args={}){
 const list=eventListItems(args);
 return `<p class="warning-result-count">本月共 ${eventsData().length} 件 · 当前显示 ${list.length} 件</p><div class="table-scroll"><table class="data-table event-list-table"><thead><tr>${eventTableColumns.map(n=>`<th scope="col">${n}</th>`).join('')}</tr></thead><tbody>${list.map((e,j)=>`<tr data-event-row="${e.id}" class="${j&&list[j-1].orgs[0]!==e.orgs[0]?'warning-group-start':''}"><td>${ORGS[e.orgs[0]].name}${e.orgs.length>1?`<small>协同：${e.orgs.slice(1).map(o=>ORGS[o].name).join('、')}</small>`:''}</td><td>${eventRiskLabel(e.cat)}</td><td>${e.title}<small class="mono">${e.id}</small></td><td class="mono">${e.date}</td><td class="mono">${e.reportTime}</td><td><span class="tag ${e.level==='高'?'red':'yellow'}">${e.level}</span></td><td>${eventProcessNodes[e.stage]}</td><td>${e.status}</td><td><button class="bare cyan" data-event="${e.id}">查看报告 ↗</button></td></tr>`).join('')||'<tr><td colspan="9" class="warning-empty">暂无符合条件的重大风险事件，请调整筛选条件。</td></tr>'}</tbody></table></div>`;
}
function eventListDetail(args={}){
 const options=(list,value)=>list.map(([id,name])=>`<option value="${id}" ${value===id?'selected':''}>${name}</option>`).join('');
 return {title:'本月重大风险事件 · '+eventsData().length+'件',body:`<p class="dialog-summary">按牵头机构、风险类型归类展示，点击“查看报告”了解事件全貌和处置进度。</p><div class="warning-filters event-list-filters"><label>机构<select id="eventOrg"><option value="all">全部机构</option>${options(activeOrgs().map(o=>[o,ORGS[o].name]),args.org)}</select></label><label>风险类型<select id="eventCategory"><option value="all">全部风险类型</option>${options(warningIndicatorTypes,args.category)}</select></label><label>关注等级<select id="eventLevel"><option value="all">全部等级</option>${options(['高','中','低'].map(v=>[v,v]),args.level)}</select></label><label>处置状态<select id="eventStatus"><option value="all">全部处置状态</option>${options([...new Set(eventsData().map(e=>e.status))].map(v=>[v,v]),args.status)}</select></label><label class="event-search-label">检索<input id="eventSearch" value="${esc(args.query||'')}" placeholder="事件名称 / 编号 / 机构"></label></div><div id="eventResults">${eventListResults(args)}</div><p class="summary-footnote">跨机构事项按事件编号仅计一次，机构栏同时展示牵头及协同机构；选择机构时包含其参与的全部事项。关注等级与指标红黄灯分别管理。全部为演示记录。</p>`};
}
function refreshEventResults(){const d=dialogStack.at(-1);$('#eventResults').innerHTML=eventListResults(d.args);syncNavigation()}
function eventReport(e){
 const scenario=eventScenarios[e.id.slice(0,5)],lead=ORGS[e.orgs[0]].name,participants=e.orgs.map(o=>ORGS[o].name).join('、'),currentStage=eventProcessNodes[e.stage],updated=eventDay(e,e.stage,'16:00');
 const actors=[lead+'风险管理岗','国资公司并表管理岗',lead+'业务及风险管理岗',participants+'相关业务岗','国资公司并表管理岗 / 集团授权复核岗','国资公司并表管理岗'];
 const feedback=[e.summary,'登记事项并明确牵头、协同机构及反馈要求；集团金融机构管理部开展业务指导。',scenario.cause+' '+(e.stage>=3?'示例方案已按授权完成审议，转入执行。':'补充事实和处置方案，按授权提交审议。'),scenario.update,'核对处置证据、剩余风险和持续管理安排，形成复核意见。','按授权确认办结并归档报告、执行记录及复核材料。'];
 const timeline=eventProcessNodes.map((name,index)=>({name,actor:actors[index],state:index<e.stage?'done':index===e.stage?'current':'pending',time:index<=e.stage?eventDay(e,index,index===0?'10:30':'16:00'):'—',feedback:index<=e.stage?feedback[index]:'待前序环节完成，尚未形成办理记录。'}));
 const measures=scenario.measures.map(([name,content,evidence],index)=>({name,content,evidence,owner:index===2?lead+'风险管理岗':lead+'业务管理岗'+(e.orgs.length>1?'（协同机构配合）':''),due:monthEnd(e.period),status:e.stage<3?'待方案确认':e.stage>=index+3?'已完成':'执行中'}));
 const updates=[{time:e.reportTime,type:'初报 V1.0',owner:lead+'风险管理岗',content:e.summary},{time:updated,type:`续报 V1.${e.stage}`,owner:lead+'风险管理岗',content:scenario.update}];
 const approval=e.stage<3?'处置方案为草案，待补充材料后按授权提交审议，尚未进入执行。':'示例方案 V1.0 已按授权履行审议后执行；集团负责授权范围内的管理决策，国资公司组织跟踪，金融机构负责执行。具体审批主体及层级以实际授权为准。';
 const attachments=[
  {id:'initial',name:'重大风险事件初报（示例）',version:'V1.0',owner:lead+'风险管理岗',time:e.reportTime,content:e.summary+'\n原因分析：'+scenario.cause+'\n影响范围：'+scenario.impact},
  {id:'plan',name:'风险事件处置方案（示例）',version:e.stage<3?'V0.1 草案':'V1.0',owner:lead+'业务及风险管理岗',time:eventDay(e,2,'16:00'),content:'处置目标：'+scenario.objective+'\n方案状态：'+approval+'\n'+measures.map((m,j)=>`${j+1}. ${m.name}：${m.content}\n责任岗位：${m.owner}；完成时限：${m.due}；执行状态：${m.status}；核验材料：${m.evidence}`).join('\n')},
  {id:'progress',name:'续报及执行进展（示例）',version:`V1.${e.stage}`,owner:lead+'风险管理岗',time:updated,content:'当前环节：'+currentStage+'\n'+scenario.update+'\n下一步：'+(e.stage<3?'完成事实核验和方案审议。':e.stage===3?'持续提交执行证据，具备条件后申请复核。':'完成剩余风险核验并按授权确认是否具备办结条件。')}
 ];
 return {...scenario,lead,participants,currentStage,updated,owner:actors[e.stage],occurred:eventDay(e,0,'08:40'),due:monthEnd(e.period),timeline,measures,updates,approval,attachments,loss:'尚未完成损失认定；待取得事实及估值、减值或实际回收依据后确认。不以投资敞口直接代替损失金额。',residual:e.stage===4?'仍需核验客户及资产口径差异的处理结果，并持续关注单体预警指标；未经复核确认不得关闭事项。':'仍需跟踪客户现金流、资产回收或风险敞口变化，以续报和执行证据更新剩余风险判断。',conclusion:'尚未办结，未形成最终办结结论；完成处置效果与证据复核，并按授权确认后方可归档。'};
}
function reportFields(pairs){return `<dl class="report-fields">${pairs.map(([name,value])=>`<dt>${name}</dt><dd>${esc(String(value))}</dd>`).join('')}</dl>`}
function eventDetail({id}){
 const e=eventsData().find(e=>e.id===id);if(!e)return {title:'本期无该事项',body:'请返回当前清单。'};
 const r=eventReport(e),sections=[['basic','基本信息'],['facts','事件经过与原因'],['impact','影响评估与风险关联'],['plan','处置方案'],['process','当前处置流程'],['updates','续报与执行进展'],['closure','复核与办结'],['materials','报告附件']];
 const section=(key,body)=>`<section class="report-section" id="event-report-${key}" tabindex="-1"><h3>${sections.find(s=>s[0]===key)[1]}</h3>${body}</section>`;
 const related=indicators.filter(i=>e.orgs.includes(i.org)&&i.cat===e.cat),warnings=warningList().filter(w=>related.some(i=>i.id===w.ind.id));
 return {title:e.title+' · 重大风险事件报告',crumb:'重大风险事件 / '+e.id,body:`<article class="event-report"><p class="report-demo">报告内容及附件均为虚构演示样例，未读取真实机构报告，不代表实际风险或审批结论。</p><div class="report-status-band"><div><span>当前处置流程环节</span><strong>${r.currentStage}</strong></div><div><span>处置状态</span><b>${e.status}</b></div><div><span>当前办理岗位</span><b>${r.owner}</b></div><div><span>下一反馈时限</span><b class="mono">${r.due}</b></div></div><div class="stream-tags">${miniOrgTags(e.orgs)}<span class="mini-tag risk-tag">${eventRiskLabel(e.cat)}</span><span class="mini-tag ${e.level==='高'?'tone-negative':'tone-neutral'}">${e.level}关注</span><span class="mini-tag">尚未办结</span></div><nav class="report-nav" aria-label="报告章节">${sections.map(([key,label])=>`<button data-report-section="${key}">${label}</button>`).join('')}</nav>
 ${section('basic',reportFields([['事件编号',e.id],['报告版本',`续报 V1.${e.stage}`],['事件名称',e.title],['风险类型',eventRiskLabel(e.cat)],['牵头机构',r.lead],['涉及机构',r.participants],['发生时间',r.occurred],['首次上报',e.reportTime],['最新更新时间',r.updated],['报告岗位',r.lead+'风险管理岗'],['组织跟踪', '国资公司并表管理岗'],['业务指导','集团金融机构管理部']]))}
 ${section('facts',reportFields([['事件经过',e.summary],['直接原因',r.cause],['深层原因与待核事项',r.root],['报告与响应','由金融机构报告事实与初步研判，国资公司组织核对和跟踪，集团在授权范围内进行指导和决策。']]))}
 ${section('impact',reportFields([['影响范围与传导',r.impact],['损失评估',r.loss],['数据核对要求','核对主体、资产、金额、期间及来源批次；区分授信额度、投资余额、监管风险暴露和实际损失。']])+`<h4>相关监测指标与预警</h4><div class="report-related">${related.map(i=>`<button class="btn" data-indicator="${i.id}">${ORGS[i.org].name} · ${i.name} ${badge(evaluate(i))}</button>`).join('')||'<span class="muted">本期没有匹配的同类指标，可通过主动报告开展处置。</span>'}${warnings.map(w=>`<button class="bare cyan" data-warning="${w.id}">查看${ORGS[w.ind.org].name}预警处置 ↗</button>`).join('')}</div><p class="summary-footnote">相关指标按机构和风险类型匹配，仅供交叉查看，不据此认定该事件由某条预警直接触发。</p>`+(e.subject?exposureHTML(e.subject):'<p class="case-note">本事项为机构敞口或限额管理事项，无单一客户对应关系。具体敞口需结合相关指标计量及业务明细核对。</p>'))}
 ${section('plan',reportFields([['处置目标',r.objective],['方案版本',e.stage<3?'V0.1 草案':'V1.0'],['审议与执行依据',r.approval],['责任分工','金融机构落实处置措施和反馈，国资公司持续跟踪及核对，集团金融机构管理部开展指导，重大事项按授权履行决策程序。']])+`<div class="table-scroll"><table class="data-table report-measures"><thead><tr><th>处置措施</th><th>具体工作</th><th>责任岗位</th><th>完成时限</th><th>执行状态</th><th>核验材料</th></tr></thead><tbody>${r.measures.map(m=>`<tr><td>${m.name}</td><td>${m.content}</td><td>${m.owner}</td><td class="mono">${m.due}</td><td>${m.status}</td><td>${m.evidence}</td></tr>`).join('')}</tbody></table></div><p class="summary-footnote">核验材料栏列示需提供的证据，不代表真实文件已上传；演示附件见报告末尾。</p>`)}
 ${section('process',`<ol class="event-process-track">${r.timeline.map(n=>`<li class="${n.state}" ${n.state==='current'?'aria-current="step"':''}><span>${n.state==='done'?'已完成':n.state==='current'?'当前环节':'待开展'}</span><b>${n.name}</b></li>`).join('')}</ol><div class="table-scroll"><table class="data-table report-flow"><thead><tr><th>流程环节</th><th>办理岗位</th><th>办理时间</th><th>反馈与结果</th></tr></thead><tbody>${r.timeline.map(n=>`<tr class="${n.state}"><td>${n.name}</td><td>${n.actor}</td><td class="mono">${n.time}</td><td>${n.feedback}</td></tr>`).join('')}</tbody></table></div>`)}
 ${section('updates',`<div class="report-updates">${r.updates.map(u=>`<div><header><b>${u.type}</b><span>${u.time} · ${u.owner}</span></header><p>${u.content}</p></div>`).join('')}</div>`+reportFields([['下一步工作',e.stage<3?'补齐事实核验材料，完善处置方案并按授权提交审议。':e.stage===3?'继续执行方案并报送证据；核验执行效果及剩余风险后申请复核。':'完成处置效果、证据与剩余风险复核，再按授权确认办结或继续整改。'],['续报要求','按确认频率反馈进展；出现风险扩大、计划偏差或重大变化时及时补报。'],['需协调事项',e.orgs.length>1?'统一跨机构主体及资产口径，协调信息反馈和处置进度；涉及重大决策的按授权提请集团审议。':'核实方案所需业务与风险数据；超出机构授权范围的事项按程序提请协调。']]))}
 ${section('closure',reportFields([['剩余风险',r.residual],['办结条件','关键处置措施落实、证据核验完成、剩余风险及持续管理安排明确，按授权形成复核和办结意见。指标灯色恢复不自动等于事件办结。'],['当前结论',r.conclusion],['归档范围','初报及续报、处置方案及审议记录、执行证据、复核意见、办结报告及后续跟踪安排。']]))}
 ${section('materials',`<div class="table-scroll"><table class="data-table report-materials"><thead><tr><th>材料名称</th><th>版本</th><th>提交岗位</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${r.attachments.map(a=>`<tr><td>${a.name}</td><td>${a.version}</td><td>${a.owner}</td><td class="mono">${a.time}</td><td><button class="bare cyan" data-event-material="${a.id}" data-report-id="${e.id}">查看内容 ↗</button></td></tr>`).join('')}</tbody></table></div><p class="summary-footnote">以上为可查看的文本演示材料，正式建设需接入完整原始报告、审批记录和附件版本。未产生的复核意见及办结报告不作为已提交附件列示。</p>`)}
 </article>`};
}
function eventMaterialDetail({id,material}){
 const e=eventsData().find(e=>e.id===id),a=e&&eventReport(e).attachments.find(a=>a.id===material);
 if(!a)return {title:'未找到材料',body:'请返回本期报告查看附件。'};
 return {title:a.name,crumb:'重大风险事件 / '+e.id+' / 报告附件',body:`<p class="report-demo">虚构文本样稿，非真实报告或已签署审批文件。</p>${reportFields([['所属事件',e.title],['版本',a.version],['提交岗位',a.owner],['更新时间',a.time]])}<div class="report-material-content">${esc(a.content)}</div>`};
}
