const riskCats=CATS.slice(0,9);
const feedState={news:{phase:0,paused:false},events:{phase:0,paused:false}};
const icons={org:'<path d="M7 26V5h17v21M3 26h25M11 10h3m3 0h3m-9 5h3m3 0h3m-9 5h3m3 0h3M13 26v-4h5v4"/>',yellow:'<path d="M15 3L29 27H1Z"/><path d="M15 11v8m0 3v2"/>',red:'<path d="M15 2l13 7v10l-13 9L2 19V9Z"/><path d="M15 8v10m0 4v2"/>',event:'<path d="M7 3h14l5 5v20H5V3Zm14 0v6h5M10 14h11M10 19h11M10 24h7"/>'};
function orgLabel(id){return id==='group'?'集团本部':ORGS[id].name}
function heading(title,tools='',sub=''){return `<div class="panel-heading"><h2><i class="heading-mark" aria-hidden="true"></i>${title}</h2><div class="heading-tools">${sub?`<small>${sub}</small>`:''}${tools}</div></div>`}
function summaryMetric(label,key,unit,tone,action,icon){const now=snapshot(state.period)[key],prior=snapshot(previousMonth(state.period))[key],delta=now-prior;return `<button class="summary-metric" data-action="${action}" style="--metric-color:var(--${tone})" aria-label="查看${label}" title="本月${now}${unit}；上月${prior}${unit}；净变化${delta}${unit}"><span class="metric-icon" aria-hidden="true"><svg viewBox="0 0 32 32">${icons[icon]}</svg></span><span class="metric-content"><span class="metric-label">${label}</span><span class="metric-number">${String(now).padStart(2,'0')}<small>${unit}</small></span><span class="metric-change">较上月 <b class="${delta>0?key==='orgs'?'cyan':'yellow':delta<0?'green':'muted'}">${delta>0?'↑ 新增 '+delta:delta<0?'↓ 减少 '+Math.abs(delta):'持平 0'}${unit}</b></span></span><span class="summary-arrow" aria-hidden="true">↗</span></button>`}
function riskFlag(severity,count){return `<span class="risk-flag flag-${severity}" ${count===undefined?'':`data-flag="${severity}" data-count="${count}"`} aria-hidden="true"><svg viewBox="0 0 38 42"><ellipse class="flag-anchor" cx="7" cy="38" rx="6" ry="1.5"/><path class="flag-mast" d="M7 4V37"/><path class="flag-cloth" d="M8 7C16 2 23 13 33 7V25C23 31 16 20 8 25Z"/>${count===undefined?'':`<text x="20.5" y="20" text-anchor="middle">${count}</text>`}</svg></span>`}
function riskSignal(status){return `<span class="flag-idle signal-${status}" data-signal="${status}" aria-hidden="true">${status==='green'?'<i></i>':status==='no_data'?'<svg viewBox="0 0 20 20"><path d="M10 3L17 10 10 17 3 10Z"/><path d="M10 7V11m0 2v1"/></svg>':status==='overdue'?'<svg viewBox="0 0 20 20"><circle cx="10" cy="10" r="7"/><path d="M10 6V10l3 2"/></svg>':'<i></i>'}</span>`}
function plantedFlag(severity,count,x){return `<g class="planted-flag flag-${severity}" data-flag="${severity}" data-count="${count}" transform="translate(${x} 0)"><path class="flag-mast" d="M0 9V47"/><path class="flag-cloth" d="M1 12C8 8 15 18 23 12V29C15 35 8 25 1 29Z"/><text x="12" y="25" text-anchor="middle">${count}</text></g>`}
function flagCoordinate(r,y,status){return `<span class="flag-coordinate" aria-hidden="true"><svg viewBox="0 0 80 60"><g class="coordinate-base"><path class="base-side" d="M12 48V53C12 61 68 61 68 53V48Z"/><ellipse class="base-top" cx="40" cy="48" rx="28" ry="7"/><ellipse class="base-ring" cx="40" cy="48" rx="20" ry="4"/><path class="base-cross" d="M36 48h8m-4-2v4"/></g>${r?plantedFlag('red',r,y?26:40):''}${y?plantedFlag('yellow',y,r?49:40):''}</svg>${!r&&!y?riskSignal(status):''}</span>`}
function heatmap(){
 const legend=`<div class="heat-legend flag-legend"><span>${riskFlag('red')}红灯</span><span>${riskFlag('yellow')}黄灯</span><span>${riskSignal('green')}正常</span><span>${riskSignal('no_data')}缺数</span><span>${riskSignal('overdue')}超期</span><span>${riskSignal('none')}未配置</span></div>`;
 const rows=activeOrgs().map(org=>`<button class="institution-label" data-org="${org}"><b>${ORGS[org].name}<span aria-hidden="true">↗</span></b></button>${riskCats.map(([cat,n])=>{
  const xs=indicators.filter(i=>i.org===org&&i.cat===cat),sts=xs.map(i=>evaluate(i)),r=sts.filter(x=>x==='red').length,y=sts.filter(x=>x==='yellow').length;
  const s=['no_data','overdue','green'].find(x=>sts.includes(x))||'none',quality=sts.includes('no_data')||sts.includes('overdue');
  const label=r||y?[r?'红灯 '+r+' 项':'',y?'黄灯 '+y+' 项':'',quality?'另有缺数或超期指标':''].filter(Boolean).join('，'):STATUS[s];
  return `<button class="heat-cell flag-cell" data-cell="${org}:${cat}" aria-label="${ORGS[org].name} ${n} ${label}" title="${ORGS[org].name} · ${n}：${label}；点击查看已预警指标">${flagCoordinate(r,y,s)}${(r||y)&&quality?'<span class="flag-quality-mark" aria-hidden="true">!</span>':''}</button>`;
 }).join('')}`).join('');
 return `${legend}<div class="heat-grid flag-matrix" style="--org-count:${activeOrgs().length}" aria-label="按机构与风险类型分布的预警插旗矩阵"><div class="heat-axis flag-axis corner">机构 / 风险类型</div>${riskCats.map(([id,n])=>`<div class="heat-axis flag-axis">${n}</div>`).join('')}${rows}</div><div class="heat-foot"><span>旗上数字为当前预警指标数；点击旗帜看预警，机构名看全部。</span><button class="bare" data-action="quality">数据状态 ↗</button></div>`;
}
function spark(i){const end=historyIndex(state.period),data=i.history.slice(Math.max(0,end-11),end+1),finite=data.filter(v=>v!==null&&Number.isFinite(v));if(finite.length<2)return '<div class="card-no-chart">暂无可用历史趋势</div>';const lo=Math.min(...finite),hi=Math.max(...finite),pad=Math.max((hi-lo)*.12,.005),y=v=>43-(v-lo+pad)/(hi-lo+2*pad)*34,x=j=>5+j/(data.length-1)*250;let path='',started=false;data.forEach((v,j)=>{if(v===null){started=false;return}path+=(started?'L':'M')+x(j).toFixed(1)+' '+y(v).toFixed(1)+' ';started=true});const last=data.at(-1),date=new Date(2023,8+end-11,1),label=date.getFullYear()+'.'+String(date.getMonth()+1).padStart(2,'0'),s=evaluate(i),stroke=['red','yellow'].includes(s)?`var(--${s})`:'#56cddd';return `<svg class="card-trend" viewBox="0 0 260 58" role="img" aria-label="${i.name}近12个月趋势"><path d="M5 45H255" stroke="#26465e" stroke-dasharray="2 3"/><path d="${path}" fill="none" stroke="${stroke}" stroke-width="2"/>${last===null?'':`<circle cx="255" cy="${y(last)}" r="2.5" fill="${stroke}"/>`}<text x="5" y="57" fill="#7196b5" font-size="8">${label}</text><text x="255" y="57" fill="#7196b5" font-size="8" text-anchor="end">${state.period.replace('-','.')}</text></svg>`}
function feedControls(kind,action){const f=feedState[kind],name=kind==='news'?'舆情':'事件';return `<div class="feed-controls"><button data-feed-step="${kind}:-1" aria-label="上一条${name}">‹</button><button data-feed-pause="${kind}" aria-label="${f.paused?'播放':'暂停'}${name}轮播">${f.paused?'▷':'Ⅱ'}</button><button data-feed-step="${kind}:1" aria-label="下一条${name}">›</button></div><button class="bare" data-action="${action}">全部 ↗</button>`}
function miniOrgTags(orgs){return orgs.map(o=>`<span class="mini-tag org-tag">${ORGS[o].name}</span>`).join('')}
function newsRows(){return sentimentData().map(s=>`<button class="stream-row news-stream-row" data-sentiment="${s.id}" title="${s.title}"><span class="stream-copy"><span class="stream-tags"><span class="mini-tag tone-${s.tone==='负面'?'negative':s.tone==='正面'?'positive':'neutral'}">${s.tone}</span>${miniOrgTags(s.orgs)}</span> <strong>${s.title}</strong></span><span class="stream-field stream-level ${s.importance>=4?'yellow':'muted'}">${s.importance>=4?'高':s.importance===3?'中':'低'}</span><span class="stream-field stream-grade">${s.importance}级</span><span class="stream-field stream-time">${s.publishedAt.slice(5,10)} ${s.time}</span><span class="row-arrow">↗</span></button>`).join('')}
function eventRows(){return eventsData().map(e=>`<button class="stream-row event-stream-row" data-event="${e.id}" title="${e.title}"><span class="stream-copy"><span class="stream-tags">${miniOrgTags(e.orgs)}<span class="mini-tag risk-tag">${catName(e.cat)}风险</span></span> <strong>${e.title}</strong></span><span class="stream-field stream-status">${e.status}</span><span class="stream-field stream-grade">${e.level}</span><span class="stream-field stream-time">${e.date.slice(5)} 10:30</span><span class="row-arrow">↗</span></button>`).join('')}
function feedColumns(kind){return kind==='news'?'<div class="stream-columns news-columns"><span>舆情信息</span><span>重要程度</span><span>等级</span><span>发布时间</span><span></span></div>':'<div class="stream-columns event-columns"><span>风险事项</span><span>处置状态</span><span>关注等级</span><span>上报时间</span><span></span></div>'}
function render(){captureFeedPositions();visibleCardIds();$('#main').innerHTML=`<section class="tier overview-tier" aria-label="并表风险纵览">${summaryMetric('并表金融机构数量','orgs','家','cyan','scope','org')}${summaryMetric('本月预警黄灯数量','yellow','项','yellow','yellow','yellow')}${summaryMetric('本月预警红灯数量','red','项','red','red','red')}${summaryMetric('本月重大风险事件数量','events','件','blue','events','event')}</section><section class="tier middle-tier" aria-label="风险热力图与关键指标"><section class="screen-panel heat-panel">${heading('风险热力图','','机构 × 风险')}${heatmap()}</section><section class="screen-panel key-panel">${heading('关键指标情况',metricTools())}<div class="metric-column-head"><span>指标名称</span><span>本月值</span><span>近12个月趋势</span><span>状态</span></div><div class="indicator-card-grid vertical-card-grid">${cards()}</div>${addMetricCard()}</section></section><section class="tier bottom-tier" aria-label="风险舆情与重大风险事项"><section class="screen-panel news-panel" id="sentimentFeed">${heading('风险舆情',feedControls('news','sentiments'))}${feedColumns('news')}${marqueeMarkup('news',newsRows())}</section><section class="screen-panel events-panel" id="eventFeed">${heading('重大风险事件',feedControls('events','events'))}${feedColumns('events')}${marqueeMarkup('events',eventRows())}</section></section>`;$('#asof').textContent=END();fitScreen();mountFeeds()}

let restoringHistory=false;
function syncNavigation(mode='replace'){syncAllFeeds();if(restoringHistory)return;const top=dialogStack.at(-1);if(top&&$('.dialog-content'))top.scrollTop=$('.dialog-content').scrollTop;history[mode==='push'?'pushState':'replaceState']({cockpitV3:true,period:state.period,stack:structuredClone(dialogStack),cardDraft:[...cardDraft],pickerQuery,pickerFilters:structuredClone(pickerFilters),cardPage},'',location.pathname+location.search+'#overview'+(top?'/'+top.type:''))}
function openDialog(type,args={},push=true){if(push)syncNavigation();if(!dialogStack.length)returnFocus=document.activeElement;if(type==='configure'&&push){cardDraft=[...selectedCards];resetPickerFilters()}if(push)dialogStack.push({type,args});const obj=dialogContent(type,args),dialogClass=({configure:'configuration-dialog',warningList:'warning-list-dialog',events:'event-list-dialog',event:'event-report-dialog',org:'org-monitoring-dialog',cell:'org-monitoring-dialog'})[type]||'';$('#modalRoot').innerHTML=`<div class="dialog-backdrop"><section class="dialog ${dialogClass}" role="dialog" aria-modal="true" aria-labelledby="dialogTitle"><div class="dialog-header"><h2 id="dialogTitle">${obj.title}</h2><button class="bare" data-action="close" aria-label="关闭弹窗">×</button></div><div class="dialog-crumb"><button data-action="dialogBack">${dialogStack.length>1?'← 返回上一级':'风险全景'}</button><span> / ${obj.crumb||obj.title}</span><span class="dialog-period">${state.period}</span></div><div class="dialog-content">${obj.body}</div></section></div>`;$('#screen').inert=true;$('[data-action="close"]',$('#modalRoot')).focus();$('.dialog-content').scrollTop=dialogStack.at(-1)?.scrollTop||0;syncNavigation(push?'push':'replace')}
function closeDialog(){dialogStack=[];$('#modalRoot').innerHTML='';$('#screen').inert=false;$('#chartTip').hidden=true;if(returnFocus?.isConnected)returnFocus.focus();syncNavigation()}
function dialogBack(){history.back()}
function replaceDialog(type,args){dialogStack[dialogStack.length-1]={type,args};openDialog(type,args,false)}
function indicatorDetail(args){const obj=baseIndicatorDetail(args),i=getInd(args.id),prev=valueAt(i,previousMonth(state.period)),v=current(i),diff=v===null||prev===null?null:v-prev;obj.crumb=ORGS[i.org].name+' / '+catName(i.cat)+' / '+i.name;obj.body=obj.body.replace('<div class="thresholds">',`<p class="indicator-mom">较上月 ${diff===null?'暂无可比数据':diff===0?'持平':`${diff>0?'上升':'下降'} ${num(Math.abs(diff),2)}${i.unit==='%'?'个百分点':i.unit}`} · 上月值 ${num(prev,2)}${i.unit}</p><div class="thresholds">`);return obj}
function warningDetail({id}){const w=warningById(id);if(!w)return {title:'事项不存在',body:'请检查观察月份。'};return {title:w.ind.name+' · 预警处置',crumb:ORGS[w.ind.org].name+' / '+id,body:`<div class="flex">${badge(w.severity)}<span class="tag">当前：${stageNames[w.stage]}</span><button class="bare cyan" data-indicator="${w.ind.id}">指标详情 ↗</button></div><div class="case-note">${w.recovered?'指标已恢复正常，需完成证据核验后办结。':'提示函面向金融机构及集团金融机构管理部下发，国资公司持续跟踪回函与整改。'}以下均为流程演示。</div><ol class="timeline">${stageNames.map((name,j)=>`<li class="${j<w.stage?'done':j===w.stage?'current':''}"><strong>${name}</strong><p>${j<=w.stage?[`${w.triggered} 系统识别并记录触发规则`,'系统生成提示函并下发机构及管理部门','机构提交原因分析、回函及初步处置安排','跟踪措施、责任岗位、完成时限及整改证据','核验剩余风险与指标恢复情况','形成结论并归档，纳入报告评价'][j]:'待前序环节完成'}</p></li>`).join('')}</ol><button class="btn" data-letter="${id}">下载预警提示函样稿</button>`}}
function exposureHTML(subjectId){const e=exposureFor(subjectId);return `<h3 class="section-label">对应主体及集团范围投资敞口</h3><div class="exposure-subject"><b>${e.name}</b><span>${e.id} · ${END()}</span></div><div class="exposure-stats"><div><span>投资敞口</span><strong>${num(e.amount,2)}<small>亿元</small></strong></div><div><span>占集团范围投资比例</span><strong>${num(e.ratio,2)}<small>%</small></strong></div><div><span>${e.rank?'客户敞口排名':'统计对象'}</span><strong>${e.rank?'第 '+e.rank+' 名':'行业汇总'}</strong><small>${e.rank?'仅在样例客户中排序':'不与单一客户混排'}</small></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>持有主体</th><th>投资类型</th><th>底层资产标识</th><th>投资敞口（亿元）</th></tr></thead><tbody>${e.rows.map(r=>`<tr><td>${orgLabel(r.org)}</td><td>${r.type}</td><td>${r.asset}</td><td class="mono">${num(r.amount,2)}</td></tr>`).join('')}</tbody></table></div><div class="case-note">演示口径：集团本部及当前纳入机构持有的相关投资账面余额，按底层资产识别去重，未按持股比例折算。比例分母为当前样例范围投资总额 ${num(e.denominator,2)} 亿元；不包含尚未使用的授信额度，不等同于融资总额、监管风险暴露或预期损失。全部为虚构样例。</div>`}
function sentimentDetail({id}){const s=sentimentData().find(s=>s.id===id);if(!s)return {title:'本期无该条资讯',body:'请返回当前月份。'};return {title:s.title,crumb:'风险舆情 / '+subjects[s.subject].name,body:`<div class="stream-tags"><span class="mini-tag tone-${s.tone==='负面'?'negative':s.tone==='正面'?'positive':'neutral'}">${s.tone}</span>${miniOrgTags(s.orgs)}<span class="mini-tag risk-tag">重要程度 ${s.importance}级</span></div><dl class="key-values"><dt>发布时间</dt><dd>${s.publishedAt}</dd><dt>信息来源</dt><dd>${s.source}（非真实新闻）</dd><dt>核查状态</dt><dd>待人工核实，不自动认定为重大风险事件</dd><dt>资讯内容</dt><dd>${s.body}</dd></dl>${exposureHTML(s.subject)}<h3 class="section-label">管理关注</h3><p class="muted">核实主体关系及信息真实性，核对相关资产、回款与风险缓释情况，再决定是否关联处置事项或发起专项报告。</p>`}}
function scopeDetail(){const previous=previousMonth(state.period);return {title:'并表金融机构与统计口径',body:`<p class="dialog-summary">集团及国资公司共用全景视图。当前${activeOrgs().length}家，上月${activeOrgs(previous).length}家。</p><div class="scope-orgs">${activeOrgs().map(o=>`<button data-org="${o}"><b>${ORGS[o].name} ↗</b><small>${ORGS[o].type}${orgScope[o]===state.period?' · 本月新增（演示）':''}</small></button>`).join('')}</div><dl class="key-values"><dt>机构范围</dt><dd>仅为交互演示范围；浦发银行自2026年7月、沪农商银行自2026年8月纳入是样例设定，不代表真实接入进度、股权关系或法定并表范围。</dd><dt>月度比较</dt><dd>本月数量减上月数量；正数显示新增，负数显示减少，零显示持平。机构数为期末范围数，预警及重大事件为当月记录数。</dd><dt>预警数量</dt><dd>按触发事项ID及触发等级去重，包含当月触发后恢复的记录。热力图只统计当前亮灯指标。</dd><dt>事件数量</dt><dd>按本月事件编号去重，同一事件涉及多家机构只计一次。</dd><dt>指标与阈值</dt><dd>全部为演示规则，不作监管合规认定。正式上线采用经批准的字典、范围与版本。</dd></dl>`}}
function qualityDetail(){const xs=institutional().filter(i=>['no_data','overdue'].includes(evaluate(i)));return {title:'数据状态核对',body:`${indicatorTable(xs)}<div class="case-note">缺数、超期、未配置与正常分别管理。采集、加工、计算与展示应可追溯；源数据真实性由供数机构负责。本演示没有连接真实供数接口。</div>`}}
function dialogContent(type,args){switch(type){case 'org':case 'cell':return orgDetail(type,args);case 'indicator':return indicatorDetail(args);case 'lineage':return lineageDetail(args);case 'warning':return warningDetail(args);case 'warningList':return warningListDetail(args);case 'event':return eventDetail(args);case 'eventMaterial':return eventMaterialDetail(args);case 'sentiment':return sentimentDetail(args);case 'scope':return scopeDetail();case 'quality':return qualityDetail();case 'configure':return configureDetail();case 'exposure':return {title:'集团范围投资敞口',body:exposureHTML(args.id||'A')};case 'events':return eventListDetail(args);case 'sentiments':return {title:'风险舆情 · 全部线索',body:`<p class="dialog-summary">资讯与投资数据均为虚构样例，重要程度为内部演示分级。</p>${feedColumns('news')}<div class="all-streams">${newsRows()}</div>`};default:return scopeDetail()}}
function refreshOrgResults(){const d=dialogStack.at(-1);$('#orgResults').innerHTML=orgResults(d.type,d.args);syncNavigation()}
document.addEventListener('click',ev=>{const b=ev.target.closest('button,[role="button"]');if(!b)return;const d=b.dataset;
 if(d.org)return openDialog('org',{org:d.org,page:0,category:'all'});
 if(d.orgSummary&&dialogStack.at(-1)?.type==='org')return selectOrgSummary(d.orgSummary);
 if(d.reportSection){const section=$('#event-report-'+d.reportSection);section?.scrollIntoView({block:'start',behavior:'instant'});section?.focus({preventScroll:true});return}
 if(d.eventMaterial)return openDialog('eventMaterial',{id:d.reportId,material:d.eventMaterial});
 if(d.cell){const [org,cat]=d.cell.split(':');return openDialog('cell',{org,cat,page:0,showAll:false})}
 if(d.indicator)return openDialog('indicator',{id:d.indicator});
 if(d.metricPage){cardPage+=Number(d.metricPage);render();syncNavigation();const target=$(`[data-metric-page="${d.metricPage}"]:not(:disabled)`);(target||$('.add-metric-card')).focus();return}
 if(d.pickerFilter){const [key,value]=d.pickerFilter.split(':');pickerFilters[key]=value==='all'?[]:pickerFilters[key].includes(value)?pickerFilters[key].filter(x=>x!==value):[...pickerFilters[key],value];return refreshPicker()}
 if(d.draftRemove){cardDraft=cardDraft.filter(id=>id!==d.draftRemove);return refreshPicker()}
 if(d.window)return replaceDialog('indicator',{...dialogStack.at(-1).args,id:d.id,window:+d.window});
 if(d.lineage)return openDialog('lineage',{id:d.lineage});
 if(d.warning)return openDialog('warning',{id:d.warning});
 if(d.event)return openDialog('event',{id:d.event});
 if(d.sentiment)return openDialog('sentiment',{id:d.sentiment});
 if(d.point)return toast(d.point+'（演示历史）');
 if(d.feedStep){const [kind,step]=d.feedStep.split(':');return advanceFeed(kind,Number(step))}
 if(d.feedPause){const f=feedState[d.feedPause];f.paused=!f.paused;b.textContent=f.paused?'▷':'Ⅱ';b.setAttribute('aria-label',(f.paused?'播放':'暂停')+(d.feedPause==='news'?'舆情':'事件')+'轮播');syncAllFeeds();return}
 if(d.orgPage){dialogStack.at(-1).args.page+=Number(d.orgPage);refreshOrgResults();return}
 if('orgSort' in d){const a=dialogStack.at(-1).args;a.sort=a.sort==='name'?'category':'name';return refreshOrgResults()}
 if('cellToggle' in d){const item=dialogStack.at(-1);return replaceDialog('cell',{...item.args,showAll:!item.args.showAll,page:0})}
 if(d.letter){const w=warningById(d.letter);download('预警提示函_演示样稿.txt',`预警提示函（演示样稿）\n接收：${ORGS[w.ind.org].name}、集团金融机构管理部\n任务组织：国资公司\n观察期：${state.period}\n指标：${w.ind.name}\n触发等级：${STATUS[w.severity]}\n当前值：${val(w.ind)}${w.ind.unit}\n请核实原因并反馈说明与整改安排。\n全部为模拟，不作为正式通知。`);return}
 switch(d.action){case 'close':return closeDialog();case 'dialogBack':return dialogBack();case 'red':case 'yellow':return openDialog('warningList',{severity:d.action});case 'scope':case 'quality':case 'configure':case 'events':case 'sentiments':return openDialog(d.action);case 'penetration':return openDialog('exposure',{id:'A'});case 'resetCards':cardDraft=[...defaultCards];return refreshPicker();case 'clearSelectedCards':cardDraft=[];return refreshPicker();case 'selectFilteredCards':return selectFilteredPickerCards();case 'clearPickerFilters':resetPickerFilters();$('#pickerSearch').value='';return refreshPicker();case 'saveCards':return saveCardSelection();case 'fullscreen':if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('当前窗口不支持全屏，页面仍按一屏展示。'));return;case 'sort':{const body=$('.dialog tbody');if(body)[...body.rows].sort((a,b)=>a.cells[1].textContent.localeCompare(b.cells[1].textContent,'zh-CN')).forEach(r=>body.append(r));return}}
});
document.addEventListener('change',ev=>{const t=ev.target;if(t.id==='period'){state.period=t.value;cardPage=0;feedState.news.phase=0;feedState.events.phase=0;closeDialog();render();syncNavigation()}if(t.id==='detailCaliber')replaceDialog('indicator',{...dialogStack.at(-1).args,id:t.dataset.id,caliber:t.value});const orgField={orgCategory:'category',orgMonitoring:'monitoring',orgStatus:'status',orgWarningScope:'periodWarnings'}[t.id];if(orgField&&['org','cell'].includes(dialogStack.at(-1)?.type)){const args=dialogStack.at(-1).args;Object.assign(args,{[orgField]:orgField==='periodWarnings'?t.value==='monthly':t.value,page:0});if(orgField==='monitoring'&&t.value!=='risk'){args.category='all';$('#orgCategory').value='all'}if(orgField==='category'&&t.value!=='all'){args.monitoring='risk';$('#orgMonitoring').value='risk'}refreshOrgResults()}const warningField={warningOrg:'org',warningMonitoring:'monitoring',warningIndicatorType:'indicatorType'}[t.id];if(warningField&&dialogStack.at(-1)?.type==='warningList'){dialogStack.at(-1).args[warningField]=t.value;refreshWarningResults()}const eventField={eventOrg:'org',eventCategory:'category',eventLevel:'level',eventStatus:'status'}[t.id];if(eventField&&dialogStack.at(-1)?.type==='events'){dialogStack.at(-1).args[eventField]=t.value;refreshEventResults()}if(t.dataset.cardChoice&&validCard(t.dataset.cardChoice)){if(!toggleCardChoice(t.dataset.cardChoice,t.checked))t.checked=false;refreshPicker()}});
document.addEventListener('input',ev=>{const t=ev.target;if(t.id==='orgSearch'){Object.assign(dialogStack.at(-1).args,{query:t.value,page:0});refreshOrgResults()}if(t.id==='eventSearch'&&dialogStack.at(-1)?.type==='events'){dialogStack.at(-1).args.query=t.value;refreshEventResults()}if(t.id==='pickerSearch'){pickerQuery=t.value;refreshPicker()}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape')closeDialog();if((ev.key==='Enter'||ev.key===' ')&&ev.target.matches('circle[role="button"]')){ev.preventDefault();ev.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}if(ev.key==='Tab'&&dialogStack.length){const els=$$('button:not(:disabled),input,select,textarea,a,[tabindex="0"]',$('.dialog')).filter(e=>e.getClientRects().length),first=els[0],last=els.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus()}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus()}}});
document.addEventListener('pointerover',ev=>{const p=ev.target.closest('[data-point]');if(p){$('#chartTip').textContent=p.dataset.point;$('#chartTip').hidden=false;$('#chartTip').style.left=Math.min(ev.clientX+14,innerWidth-270)+'px';$('#chartTip').style.top=Math.max(10,ev.clientY-40)+'px'}});document.addEventListener('pointerout',ev=>{if(ev.target.matches('[data-point]'))$('#chartTip').hidden=true});
function fitScreen(){const scale=Math.min(1,innerWidth/1440,innerHeight/810),s=$('#screen');s.style.width=innerWidth/scale+'px';s.style.height=innerHeight/scale+'px';s.style.transform=`scale(${scale})`}
function resizeScreen(){captureFeedPositions();fitScreen();mountFeeds()}
window.addEventListener('resize',resizeScreen);document.addEventListener('fullscreenchange',resizeScreen);
window.addEventListener('popstate',ev=>{if(!ev.state?.cockpitV3)return;restoringHistory=true;try{state.period=ev.state.period;$('#period').value=state.period;cardDraft=cleanCardIds(ev.state.cardDraft);pickerQuery=ev.state.pickerQuery||'';pickerFilters=ev.state.pickerFilters||{org:[],risk:[],type:[]};cardPage=ev.state.cardPage||0;dialogStack=structuredClone(ev.state.stack||[]);render();const top=dialogStack.at(-1);if(top)openDialog(top.type,top.args,false);else closeDialog()}finally{restoringHistory=false}});
function clock(){const t=new Date();$('#clock').textContent=t.toLocaleDateString('zh-CN').replaceAll('/','.')+'  '+t.toLocaleTimeString('zh-CN',{hour12:false})}clock();setInterval(clock,1000);
function openEntryFromQuery(){const params=new URLSearchParams(location.search),entry=params.get('entry'),org=params.get('org'),cat=params.get('cat'),id=params.get('id');
 if(entry==='org'&&org&&ORGS[org])return openDialog('org',{org,page:0,category:'all'});
 if(entry==='cell'&&org&&ORGS[org]&&cat&&CATS.some(([key])=>key===cat))return openDialog('cell',{org,cat,page:0,showAll:false});
 if(entry==='indicator'&&id&&getInd(id))return openDialog('indicator',{id});
 if(entry==='quality')return openDialog('quality');
 if(entry==='configure')return openDialog('configure');
}
localData={};render();syncNavigation();openEntryFromQuery();
window.__cockpit={state,indicators,evaluate,counts,warningList,snapshot,activeOrgs,previousMonth,eventsData,sentimentData,exposureFor,orgItems,feedState,advanceFeed,marqueePlayers,getSelectedCards:()=>[...selectedCards],getActiveCards:activeCardIds,getDialogStack:()=>structuredClone(dialogStack)};
